name: Publish Image

on:
  push:
    tags:
    - '*'

env:
  REGISTRY_URL: registry.aity.tech

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY_URL }}
        username: ${{ secrets.MONTY_REGISTRY_USERNAME }}
        password: ${{ secrets.MONTY_REGISTRY_PASSWORD }}
    - if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        echo TAG_NAME=$(echo $GITHUB_REF | sed -e "s|refs/tags/||") >> $GITHUB_ENV
    - name: Build and push collector
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY_URL }}/monty/monty-otel-collector:${{ env.TAG_NAME }}-0.85.0